dhis2/cli-utils-cypress

.github/workflows/node-lint.yml
.github/workflows/node-publish.yml
package.json
yarn.lock

Related to: https://github.com/dhis2/cli/pull/302
Also updates the workflows to the latest template.
BREAKING CHANGE: Require Node version 10 or above.

chore: update node engine to >= 10

---

helper.js
helper/dataTestNameToSelector.js
helper/parseSelectorWithDataTest.js
src/commands/install.js
support.js

This PR will add three things:
Having to write out the data test selector, especially when using several of them in one query, made the test code look quite bloated and much harder to parse when reading through it.
I've extracted this from the @dhis2/ui-core#639 branch, where I created a substitute syntax for writing selectors with data-test props, so these are all equivalent pairs:
```js
cy.get('[data-test="dhis2-uicore-transfer-sourceoptions"] [data-test="dhis2-uicore-transferoption"]')
cy.get('{transfer-sourceoptions} {transferoption}')
cy.get('[data-test="dhis2-uicore-transfer-filter"] input')
cy.get('{transfer-filter} input')
cy.get('.some-element').find('[data-test="dhis2-uicore-transfer-sourceoptions"] [data-test="dhis2-uicore-transferoption"]') …
```

feat: add custom data-test selector syntax

---

package.json
src/commands/common/sharedCLIOptions.js
src/commands/install.js
src/commands/install/createCucumberConfigs.js
src/commands/install/createCypressConfig.js
src/commands/install/createCypressEnvConfig.js
src/commands/install/createCypressSupportFile.js
src/commands/install/ensureDirectories.js
src/commands/open.js
src/commands/run.js
src/tools/cypress.js
src/tools/execCypress.js
src/tools/getCypressCommand.js
src/tools/waitOnAndCypress.js
src/utils/fs.js
src/utils/paths.js
yarn.lock

BREAKING CHANGE: The `d2-utils-cypress open` and `d2-utils-cypress run` now use `concurrently` and `wait-on` by default. If new behavior is undesired, it can be disabled with `--appStart ''`.
This PR does 3 things
1. refactors the `install` command's code
2. only writes the `testFiles` config to the `cypress.json` when using cucumber
3. Uses `concurrently` and `wait-on` when using the `open` and `run` commands

feat: add concurrently & wait-on command

---

support.js

Fixes include:
* correct login url
* add `form` and `followRedirect` properties
* remove the auth header since it isn't needed for logging in

fix: correct url and needed props for login command

---

packages/cypress-commands/package.json

Semantic release fails with
> `npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@dhis2%2fcypress-commands - You must sign up for private packages`
This is because I didn't add the `publishConfig` section to the package.json of the cypress-commands subpackage, see [here](https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-set-the-access-level-of-the-published-npm-package).

fix(cypress commands release): add publish config to package.json

---

.github/workflows/node-publish.yml
package.json

The published package does not have the `build` directory.
I hope this will add the build directory and is not ignored because of the `.gitignore`.

fix(cypress commands release): run build script before deploying

---

packages/cypress-commands/src/commands/login.js

Current code causes login to fail if there is no `server` input field (will be the case when REACT_APP_DHIS2_BASE_URL is defined along side CYPRESS_DHIS2_BASE_URL)
https://docs.cypress.io/guides/core-concepts/conditional-testing.html#Element-existence

fix: check the length as find always returns an object

---

packages/cypress-commands/src/commands/login.js

Updates the target of the login button, as it has changed from `data-test="dhis2-uicore-button"` to `data-test="dhis2-adapter-loginsubmit"`, which causes the login fn to fail (screenshot)

fix: update the login button target

---

packages/cli/src/tools/waitOnAndCypress.js

Fixes TECH-472
This will make sure that the `d2 utils cypress run` command exits properly.
The previous `concurrently` configuration didn't cause the process to exit when the `run` process has finished in some cases

fix(run command): make command exit correctly

---

packages/cli/src/commands/install/ensureDependency.js

The command `d2-utils-cypress install` would not complete successfully in a yarn workspaces repo due to the missing `-W` flag. This fixes it, but I wonder if there would be a more elegant way to do this...

fix(commands): add `-W` to `yarn add` when in yarn workspaces root

---

package.json

We should also build the plugins 😺

fix: build both commands and plugins when running yarn build

---

package.json
packages/cli/package.json
packages/cypress-commands/package.json
yarn.lock

jscodeshift is not a dev dependency as it is used in the install command

fix(commands): move jscodeshift to regular dependencies

---

packages/cypress-commands/codemods/replace-get-find-with-xxxxGetWithDataTest.js

This adds some checks to the callback functions to prevent errors from being thrown when trying to access a property of undefined.
OT: man.. optional chaining would be SO nice here..

fix(replace getfind mod): add checks to prevent crashes

---

examples/platform-app/package.json
examples/testing-network-shim-app/package.json
packages/cli/package.json
yarn.lock

Possibly the problem we have been seeing in the sms-configuration-app was to do with https://github.com/cypress-io/cypress/issues/16451, which is fixed in v7.4.0. So it's worth trying this before digging further.

chore(deps): bump cypress from 7.3.0 to 7.4.0

---

packages/cypress-commands/src/setups/enableNetworkShim/index.js
packages/cypress-plugins/src/plugins/networkShim/index.js

CLI-48 turns out to be a regression from yesterday #201. It has to do with the fact that state changes during a test in a stub run (it’s always done that) and state now also being persisted across tests in a stub run (it used to do this in capture mode only).
I considered two options for addressing this issue:
1. The current solution which keeps using the state to keep track of missing request stubs across features
2. A more involved, but arguably cleaner, solution which would involve keeping track of missing request stubs during stub mode via a dedicated state object. 
I opted for 1 because this doesn't require as many changes, and hope the comments compensate somewhat for the complicated logic.

fix(network-shim): only incrementally update missing request stub state

---

packages/cli/src/commands/run.js

The fact that we were using Chrome for cypress runs was a relic of the past that should have been removed. At some point in time, the Network Shim did not have support for 304 requests and to work around this issue I was using Chrome and passing a flag to it to disable the network caching. I had to use Chrome because it wasn't possible to disable the Electron network cache with a flag.
However, I have added support for 304 requests quite a while ago, so we should use Electron instead since that comes with cypress and is therefore guaranteed to be available. I have simply removed the default field, because I think it is best if we use whichever browser cypress uses as default for runs, so I didn't want to set it explicitly in our CLI command.
For reference, here is the part of the code …

fix(network-shim): use electron instead of chrome for runs

---

packages/cli/package.json

BREAKING CHANGE: New minimum version for NodeJS is 12.x.

chore: remove node 10 support

---

docs/_sidebar.md
docs/guides/using-the-network-shim.md
examples/platform-app/package.json
examples/testing-network-shim-app/package.json
yarn.lock

I think these docs cover everything that's required. Writing docs is not something I do often, so please don't hesitate to correct me.
One thing I was wondering about is wether or not we need to add anything under `docs/setups`... The `enableNetworkShim` falls under `setups` too and is currently missing. However, I don't think it's very useful to document this in isolation. The function doesn't even accept any arguments so there is hardly anything to document.
On the other hand, it may be weird that we have two "setups" but only one of them has its own documentation page. Perhaps We just add a file that refers readers to the guide?

docs(network-shim): add guide explaining usage and configuration

---

packages/cypress-commands/src/setups/enableNetworkShim/captureRequests.js
packages/cypress-commands/src/setups/enableNetworkShim/index.js
packages/cypress-plugins/src/plugins/networkShim/index.js

This is a follow-up on #261. I guess the approval app test suite is the first place where we had to deal with repeating requests to the same endpoint that would return a mixture of 304 and 200 responses. In any case, I uncovered 2 bugs. I'll place some comments in the code to explain.
Before merging this in, I think I'd like to check what would happen if we apply these changes in isolation, without the changes from #261. I _think_ both PRs are required, but it could also be possible that the changes in the current PR are actually all that was needed.

fix(network-shim): ensure 304s are dealth with correctly

---

examples/testing-network-shim-app/package.json
package.json
packages/cli/jest.config.js
packages/cli/package.json
packages/cypress-commands/jest.config.js
packages/cypress-commands/package.json
packages/cypress-commands/src/setups/enableNetworkShim/utils.js
packages/cypress-commands/src/setups/enableNetworkShim/utils.test.js
packages/cypress-plugins/package.json
yarn.lock

BREAKING CHANGE: Adds cypress with min version 8.2 as peer dependency

fix: use stable "Cypress.currentTest" in networkshim "getFeatureName" util

---

packages/cypress-commands/src/setups/enableNetworkShim/index.js
packages/cypress-commands/src/setups/enableNetworkShim/waitForResources.js

Background: Some of our tests were quite flaky. The cause is that some of the requests of the app are being fired when the test is actually done which causes them to not get recorded. When running cypress in stub mode, this produces an error as we're stubbing all requests of a certain url (which applies to requests that run during cypress' internal `after each` hook).
This PR adds a `waitForRequests` command that's being used before storing the captured requests.

fix(network shim): wait for network idle after tests

---

packages/cypress-plugins/src/plugins/networkShim/createFixturesFromState.js

replaceAll is supported in nodejs >= v15. Many still use node v12 oder
node v14, so this removes the issue for having to install node v15
just for this function call

fix(create fixtures from state): use `replace` instead of `replaceAll`

---

examples/platform-app/cypress.env.json
examples/platform-app/cypress/fixtures/network/42/creating_user_groups_with_intercept_and_fixture.json
examples/platform-app/cypress/fixtures/network/42/handles_304s_in_a_single_feature.json
examples/platform-app/cypress/fixtures/network/42/static_resources.json
examples/platform-app/cypress/fixtures/network/42/summary.json
examples/platform-app/cypress/fixtures/network/42/the_app_lists_user_groups.json
packages/cypress-commands/src/commands/loginByApi.js

- Fixes [DHIS2-17212](https://dhis2.atlassian.net/browse/DHIS2-17212)
--------------
**Description:**
- From the discussion in the above ticket, app versions 41+ can make use of the new endpoints. 
- The implementation in this PR checks for the `loginConfig`, and if it exists (v41+), login happens via the new login endpoint. 
- If it does not (v40 and below), login happens via the old login endpoint. 
**How to test:**
To test, run `yarn cy:local`
[DHIS2-17212]: https://dhis2.atlassian.net/browse/DHIS2-17212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(loginByAPI): update loginByApi cypress command to support v42

---

packages/cypress-commands/src/commands/loginByApi.js

- The command no longer relies on a seemingly unrelated endpoint to infer the correct major version of the backend.
- The amount of requests needed to login is also reduced because the correct login mechanism is stored as a Cypress env var, which will remain available for the entire run
- And finally, the command will now always yield a response, which can be asserted, like so:
```js
cy.loginByApiV2({ username, password, baseUrl })
.its('status')
.should('equal', 200)
```
Some notes:
- We have tried this new login mechanism in one of the analytics-apps. It works fine there, see: https://github.com/dhis2/data-visualizer-app/pull/3388
- But in our analytics apps we have stopped using the `enabledAutoLogin()` helper and we are now using this `cy.loginByApi()` command directly. So perhaps it …

feat: improve login by api command
